//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExitInterview
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string ReasonForLeaving { get; set; }
        public Nullable<System.DateTime> ExpectedResignDate { get; set; }
        public Nullable<bool> IsAcceptedAnotherPosition { get; set; }
        public string MotivationForJobChanges { get; set; }
        public string JobSearchStartFrom { get; set; }
        public string AttractiveFactors { get; set; }
        public string CareerGoalsElseWhere { get; set; }
        public string CareerGoalDiscussion { get; set; }
        public Nullable<bool> IsCareerOpportunitiesSatisfaction { get; set; }
        public Nullable<bool> IsPromotionalOpportunities { get; set; }
        public Nullable<bool> IsPositionRotations { get; set; }
        public Nullable<bool> IsIncreasedResponsibilities { get; set; }
        public Nullable<bool> IsSpecialProjects { get; set; }
        public Nullable<bool> IsOverseas { get; set; }
        public Nullable<bool> IsNoProgression { get; set; }
        public Nullable<bool> IsOther { get; set; }
        public Nullable<int> RatingJobResponsibilities { get; set; }
        public Nullable<int> RatingGoalOpportunities { get; set; }
        public Nullable<int> RatingWorkEnvironment { get; set; }
        public Nullable<int> RatingManager { get; set; }
        public Nullable<int> RatingPay { get; set; }
        public Nullable<int> RatingBenefits { get; set; }
        public string JobEnjoyment { get; set; }
        public string JobChallenges { get; set; }
        public string PositiveAspectsOfWorkPlace { get; set; }
        public string NegativeAspectsOfWorkPlace { get; set; }
        public string WorkplaceImprovementSuggestions { get; set; }
        public Nullable<bool> IsConsideredStaying { get; set; }
        public int Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
