//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncentiveDistributionDetail
    {
        public long Id { get; set; }
        public int IncentiveDistributionChartId { get; set; }
        public double PromotionalPercentage { get; set; }
        public bool IsSalesPersone { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public long EmployeeId { get; set; }
        public int CompanyId { get; set; }
    }
}
