//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncentiveProcessMaster
    {
        public long Id { get; set; }
        public long CGId { get; set; }
        public int Month { get; set; }
        public int Years { get; set; }
        public int CompanyId { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public double CollactionPersetage { get; set; }
        public decimal IncentiveAmt { get; set; }
        public double IncentivePersetage { get; set; }
    }
}
