//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueMasterInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IssueMasterInfo()
        {
            this.IssueDetailInfoes = new HashSet<IssueDetailInfo>();
        }
    
        public long IssueMasterId { get; set; }
        public string IssueNo { get; set; }
        public System.DateTime IssueDate { get; set; }
        public long IssuedBy { get; set; }
        public int VendorId { get; set; }
        public int CompanyId { get; set; }
        public string Remarks { get; set; }
        public bool IsSubmit { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Achknolagement { get; set; }
        public long AchknologeBy { get; set; }
        public Nullable<System.DateTime> AcknologeDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueDetailInfo> IssueDetailInfoes { get; set; }
    }
}
