//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KGCompanyMonthlySaleTerget
    {
        public long KGCompanyMonthlySaleTergetId { get; set; }
        public long KGCompanySaleTergetId { get; set; }
        public int Month { get; set; }
        public decimal MonthlySalesTergetedAmount { get; set; }
        public Nullable<decimal> MonthlyTergetedQuantity { get; set; }
        public decimal MonthlyCollectionTergetedAmount { get; set; }
        public int UnitId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
