//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KGSalesAchivementDetail
    {
        public long KGSalesAchievementDetailsId { get; set; }
        public long KGCompanyMonthlySaleTergetId { get; set; }
        public long EmployeeId { get; set; }
        public decimal GrossSalleryAmount { get; set; }
        public decimal SalesAchievementAmount { get; set; }
        public decimal SalesAchievementQuantity { get; set; }
        public decimal RecoveryAchievementAmount { get; set; }
        public decimal SalesTargetAmount { get; set; }
        public decimal SalesTargetQty { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public decimal TargetCollectionAmount { get; set; }
    }
}
