//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCAmendment
    {
        public long LCAmendmentId { get; set; }
        public long LCId { get; set; }
        public System.DateTime AmendmentDate { get; set; }
        public decimal AmendmentValue { get; set; }
        public bool IsIncrase { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsSubmit { get; set; }
        public string Remark { get; set; }
    }
}
