//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCInfo
    {
        public long LCId { get; set; }
        public string LCNo { get; set; }
        public System.DateTime LCDate { get; set; }
        public int CompanyId { get; set; }
        public int CompanyBankBranchId { get; set; }
        public int SupplierId { get; set; }
        public int SupplierBankBranchId { get; set; }
        public int LCType { get; set; }
        public string PINo { get; set; }
        public Nullable<System.DateTime> PIDate { get; set; }
        public decimal LCValue { get; set; }
        public decimal LCValueInBDT { get; set; }
        public Nullable<int> ProductOriginId { get; set; }
        public int CountryofOriginId { get; set; }
        public int PortOfLoadingId { get; set; }
        public int CountryOfDestinationId { get; set; }
        public int PortOfDischargeId { get; set; }
        public string NotefyParty { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public System.DateTime ExparyDate { get; set; }
        public Nullable<decimal> AmendmentIncrase { get; set; }
        public Nullable<decimal> AmendmentDiccrase { get; set; }
        public Nullable<decimal> CashMarginPercent { get; set; }
        public Nullable<decimal> CashMarginAmount { get; set; }
        public Nullable<decimal> BankCharge { get; set; }
        public Nullable<decimal> InsuranceValue { get; set; }
        public Nullable<decimal> CommissionValue { get; set; }
        public Nullable<decimal> FreightCharges { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public int CurrenceyId { get; set; }
        public decimal CurrenceyRate { get; set; }
        public string PaymentTerms { get; set; }
        public string ShippingMark { get; set; }
        public int VesselId { get; set; }
        public bool IsActive { get; set; }
        public int Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> AccountingHeadId { get; set; }
        public int AdvanceOrLoanGLId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
