//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialReceiveDetail
    {
        public long MaterialReceiveDetailId { get; set; }
        public Nullable<long> MaterialReceiveId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public decimal ReceiveQty { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Deduction { get; set; }
        public Nullable<decimal> StockInQty { get; set; }
        public Nullable<decimal> StockInRate { get; set; }
        public Nullable<int> BagId { get; set; }
        public Nullable<decimal> BagWeight { get; set; }
        public int BagQty { get; set; }
        public int PurchaseOrderDetailFk { get; set; }
        public bool IsReturn { get; set; }
        public decimal VATAddition { get; set; }
        public decimal ProductDiscount { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string LotNumber { get; set; }
    
        public virtual MaterialReceiveDetail MaterialReceiveDetail1 { get; set; }
        public virtual MaterialReceiveDetail MaterialReceiveDetail2 { get; set; }
    }
}
