//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRoll_Signatory
    {
        public int SignatoryId { get; set; }
        public string SignatoryName { get; set; }
        public int EmployeeId { get; set; }
        public string SignatoryType { get; set; }
        public int CompanyId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int Priority { get; set; }
        public bool IsActive { get; set; }
        public bool IsDispaly { get; set; }
        public int OrderBy { get; set; }
    }
}
