//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreservingAuditDocument
    {
        public long ID { get; set; }
        public int CompanyId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Type { get; set; }
        public string ProcedureeApplied { get; set; }
        public string Observation { get; set; }
        public string AuditRecommendationPrimary { get; set; }
        public string ConcernedFeedback { get; set; }
        public string AuditRecommendationFinal { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string DocumentNo { get; set; }
        public string Title { get; set; }
    }
}
