//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRoll_SalaryConfiguration
    {
        public long SalaryConfigurationId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public decimal Basic { get; set; }
        public decimal HouseRent { get; set; }
        public decimal Medical { get; set; }
        public decimal Transportation { get; set; }
        public decimal MobileBill { get; set; }
        public decimal Gross { get; set; }
        public decimal Welfare_D { get; set; }
        public decimal ProvidentFund_D { get; set; }
        public decimal Tax_D { get; set; }
        public decimal Rent_D { get; set; }
        public decimal TransportationAddition { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsBonusAllowed { get; set; }
    }
}
