//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRoll_AttendanceModifiedLog
    {
        public long Id { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string PreviousLog { get; set; }
        public string NewLog { get; set; }
        public string EmployeeId { get; set; }
        public string MonthAndYear { get; set; }
        public int CompanyId { get; set; }
    }
}
