//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealStateMessage
    {
        public long ID { get; set; }
        public int CompanyId { get; set; }
        public int Agenda { get; set; }
        public int MediaType { get; set; }
        public string Message { get; set; }
        public string Address { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public int Status { get; set; }
        public bool IsActive { get; set; }
        public int TryCount { get; set; }
        public string TrackId { get; set; }
        public string SMSLog { get; set; }
    }
}
