//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateReturn
    {
        public long ReturnId { get; set; }
        public long CGId { get; set; }
        public string Particular { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public long IsAccAproval { get; set; }
        public Nullable<System.DateTime> AccAprovalDate { get; set; }
        public long DocId { get; set; }
        public decimal ReturnFee { get; set; }
        public decimal ReturnFeePercentage { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
