//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionSignatory
    {
        public long RequisitionSignatoryId { get; set; }
        public long EmployeeId { get; set; }
        public long SignatoryEmpId { get; set; }
        public string DesignationName { get; set; }
        public int OrderBy { get; set; }
        public bool IsHRAdmin { get; set; }
        public string IntegrateWith { get; set; }
        public decimal Limitation { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
