//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTransferDetail
    {
        public long SalesTransferDetailsId { get; set; }
        public long SalesTransferId { get; set; }
        public long OrderDeliverDetailId { get; set; }
        public int ProductId { get; set; }
        public string LotNumber { get; set; }
        public Nullable<decimal> TransferQuantity { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
