//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTransfer
    {
        public long SalesTransferId { get; set; }
        public System.DateTime SalesTransferDate { get; set; }
        public string SalesTransferNo { get; set; }
        public long OrderMasterId { get; set; }
        public long OrderDeliverId { get; set; }
        public int FromVendorId { get; set; }
        public int ToVendoerId { get; set; }
        public int CompanyId { get; set; }
        public bool IsSubmited { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
