//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeedProcessing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeedProcessing()
        {
            this.SeedProcessingDetails = new HashSet<SeedProcessingDetail>();
        }
    
        public long SeedProcessingId { get; set; }
        public string SeedProcessNo { get; set; }
        public Nullable<System.DateTime> SeedProcessDate { get; set; }
        public string SeedProcessBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<int> HeadGLId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeedProcessingDetail> SeedProcessingDetails { get; set; }
    }
}
