//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShereMember
    {
        public int MemberID { get; set; }
        public string MemberNo { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string HusbandName { get; set; }
        public string MotherName { get; set; }
        public string CurrentAddress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Religion { get; set; }
        public string Division { get; set; }
        public string Diistrict { get; set; }
        public string Village { get; set; }
        public string PostOffice { get; set; }
        public string PoliceStation { get; set; }
        public string District { get; set; }
        public string Recommended { get; set; }
        public string AcccountNo { get; set; }
        public string ParmPhone { get; set; }
        public string Nationality { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public System.DateTime DOB { get; set; }
        public string MarritalStatus { get; set; }
        public int Children { get; set; }
        public string HeirName { get; set; }
        public string HeirAddress { get; set; }
        public double Age { get; set; }
        public string Relationship { get; set; }
        public Nullable<int> MemberStatus { get; set; }
        public string Share { get; set; }
        public string Seaco_HeadID { get; set; }
        public double OpenBalane { get; set; }
        public Nullable<double> SecendVershon { get; set; }
    }
}
