//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public long WorkId { get; set; }
        public long ManagerId { get; set; }
        public string WorkNo { get; set; }
        public string Title { get; set; }
        public bool IsWatched { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ExpectedEndDate { get; set; }
        public int Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> WorkLabelId { get; set; }
        public long WorkBoardId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual WorkState WorkState { get; set; }
    }
}
