//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualPerformance
    {
        public long AnnualPerformanceId { get; set; }
        public string APRNO { get; set; }
        public System.DateTime AssessmentFrom { get; set; }
        public System.DateTime AssessmentTo { get; set; }
        public string Remarks { get; set; }
        public bool IsSubmitted { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> AprEndDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
