//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralRequisition
    {
        public long Id { get; set; }
        public string RequisitionNumber { get; set; }
        public System.DateTime RequisitionDate { get; set; }
        public int GRequisitionType { get; set; }
        public Nullable<int> RequisitionToCompanyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> GRequisitionCategoryId { get; set; }
        public string Remarks { get; set; }
        public long EmployeeId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsAsset { get; set; }
        public decimal AITParcent { get; set; }
        public decimal DiscountParcent { get; set; }
    }
}
