//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRoll_AttendanceLogDetail
    {
        public long AttendanceLogDetail { get; set; }
        public long AttendanceLogId { get; set; }
        public long EmployeeId { get; set; }
        public int CompanyId { get; set; }
        public int DepartmentId { get; set; }
        public int EarlyOut { get; set; }
        public int LateIn { get; set; }
        public int LateInEarlyOut { get; set; }
        public int Absent { get; set; }
        public int OnTime { get; set; }
        public int Present { get; set; }
        public int Leave { get; set; }
        public int LeaveWithoutPay { get; set; }
        public int OnField { get; set; }
        public int Tour { get; set; }
        public int OffDay { get; set; }
        public int Holiday { get; set; }
        public int DeductedDay { get; set; }
        public int PayableDay { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
