//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCreditCollection
    {
        public long ShortCreditCollectionId { get; set; }
        public int VendorId { get; set; }
        public decimal CollectedAmount { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public int BankHeadId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> VoucherId { get; set; }
        public decimal BankCharge { get; set; }
        public bool IsSubmitted { get; set; }
        public int CompanyId { get; set; }
    }
}
