//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignatoryApprovalMap
    {
        public long SignatoryApprovalMapId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public long IntregratedFromId { get; set; }
        public string TableName { get; set; }
        public int OrderBy { get; set; }
        public int Status { get; set; }
        public string Comment { get; set; }
        public bool IsHRAdmin { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
