//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGERP.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRequisition
    {
        public int VehicleRequisitionId { get; set; }
        public int ResponsibleOfficerId { get; set; }
        public int DayId { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public int TotalPersion { get; set; }
        public int PrijectId { get; set; }
        public int CompanyId { get; set; }
        public string Reason { get; set; }
        public string Location { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string DriverName { get; set; }
    }
}
